spring:
  datasource:
    url: jdbc:mysql://35.192.69.214:3306/amitie_db?serverTimezone=UTC&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:log4jdbc:mysql://localhost:3306/block_board?serverTimezone=UTC&characterEncoding=utf8
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: blockboard
      password: root
  mybatis:
    type-aliases-package: com.project.amitie.mapper
    mapper-locations: mybatis/mapper/**/*.xml
