spring:
  profiles:
    active: dev # 기본 환경 선택

--- # dev 환경

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/amitie_db?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dongwook
    password: dongwook

mybatis:
  type-aliases-package: com.project.amitie.mapper
  mapper-locations: mybatis/mapper/**/*.xml


# SQL Log 볼 때 사용하는 옵션
logging:
  level:
    jdbc.sqlonly: info
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: warn


