spring:
  profiles:
    active: release # 기본 환경 선택

--- # 운영 환경
spring:
  profiles: release

  datasource:
    url: jdbc:mysql://35.192.69.214:3306/amitie_db?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dongwook
    password: dongwook

    mybatis:
      type-aliases-package: com.project.amitie.mapper
      mapper-locations: mybatis/mapper/**/*.xml

